#############################################################################
# Makefile for building: host-switcher
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? 5? 11 11:30:08 2011
# Project:  host_switcher.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile host_switcher.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = host_switcher.cpp \
		host_config.cpp \
		main.cpp moc_host_switcher.cpp \
		qrc_host_switcher.cpp
OBJECTS       = host_switcher.o \
		host_config.o \
		main.o \
		moc_host_switcher.o \
		qrc_host_switcher.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		host_switcher.pro
QMAKE_TARGET  = host-switcher
DESTDIR       = 
TARGET        = host-switcher

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_host_switcher.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: host_switcher.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile host_switcher.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile host_switcher.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/host-switcher1.0.0 || $(MKDIR) .tmp/host-switcher1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/host-switcher1.0.0/ && $(COPY_FILE) --parents host_switcher.h host_config.h .tmp/host-switcher1.0.0/ && $(COPY_FILE) --parents host_switcher.qrc .tmp/host-switcher1.0.0/ && $(COPY_FILE) --parents host_switcher.cpp host_config.cpp main.cpp .tmp/host-switcher1.0.0/ && $(COPY_FILE) --parents host_switcher.ui .tmp/host-switcher1.0.0/ && (cd `dirname .tmp/host-switcher1.0.0` && $(TAR) host-switcher1.0.0.tar host-switcher1.0.0 && $(COMPRESS) host-switcher1.0.0.tar) && $(MOVE) `dirname .tmp/host-switcher1.0.0`/host-switcher1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/host-switcher1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_host_switcher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_host_switcher.cpp
moc_host_switcher.cpp: ui_host_switcher.h \
		host_config.h \
		host_switcher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) host_switcher.h -o moc_host_switcher.cpp

compiler_rcc_make_all: qrc_host_switcher.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_host_switcher.cpp
qrc_host_switcher.cpp: host_switcher.qrc \
		images/switch.png
	/usr/bin/rcc -name host_switcher host_switcher.qrc -o qrc_host_switcher.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_host_switcher.h
compiler_uic_clean:
	-$(DEL_FILE) ui_host_switcher.h
ui_host_switcher.h: host_switcher.ui
	/usr/bin/uic-qt4 host_switcher.ui -o ui_host_switcher.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

host_switcher.o: host_switcher.cpp host_switcher.h \
		ui_host_switcher.h \
		host_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o host_switcher.o host_switcher.cpp

host_config.o: host_config.cpp host_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o host_config.o host_config.cpp

main.o: main.cpp host_switcher.h \
		ui_host_switcher.h \
		host_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_host_switcher.o: moc_host_switcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_host_switcher.o moc_host_switcher.cpp

qrc_host_switcher.o: qrc_host_switcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_host_switcher.o qrc_host_switcher.cpp

####### Install

install_images: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/host-switcher/images/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/host-switcher/images/ 
	-$(INSTALL_FILE) /home/yyquick/workspace/host-switcher/images/switch.ico $(INSTALL_ROOT)/usr/local/host-switcher/images/
	-$(INSTALL_FILE) /home/yyquick/workspace/host-switcher/images/switch.png $(INSTALL_ROOT)/usr/local/host-switcher/images/


uninstall_images:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/host-switcher/images/switch.ico 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/host-switcher/images/switch.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/host-switcher/images/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/yyquick/workspace/host-switcher/install/hostswitcher.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/hostswitcher.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_launcher: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/host-switcher/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/host-switcher/ 
	-$(INSTALL_PROGRAM) /home/yyquick/workspace/host-switcher/hs-launcher $(INSTALL_ROOT)/usr/local/host-switcher/


uninstall_launcher:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/host-switcher/hs-launcher
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/host-switcher/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/host-switcher/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/host-switcher/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/host-switcher/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/host-switcher/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/host-switcher/ 


install:  install_images install_desktop install_launcher install_target  FORCE

uninstall: uninstall_images uninstall_desktop uninstall_launcher uninstall_target   FORCE

FORCE:

